# Generated by Django 5.0.3 on 2024-03-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.TextField(db_column="fname", max_length=20)),
                ("last_name", models.TextField(db_column="lname", max_length=20)),
                ("subject", models.TextField(db_column="subject", max_length=200)),
                ("message", models.TextField(db_column="message", max_length=500)),
                ("email", models.TextField(db_column="email", max_length=20)),
                ("phone", models.TextField(db_column="phone", max_length=20)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
