# Generated by Django 5.0.3 on 2024-03-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.TextField(db_column="user_id", max_length=10, null=True),
        ),
    ]
